services:
  db:
    image: mysql:8.0
    container_name: event_reservation_container
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "1111"
      MYSQL_DATABASE: event_reservation

  redis:
    image: redis:latest
    container_name: event_reservation_redis_container
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/data
      - ./redis/conf/redis.conf:/usr/local/conf/redis.conf
    command: redis-server /usr/local/conf/redis.conf

volumes:
  mysql_data:
  redis_data: